[tool.poetry]
name = "asynq-py"
version = "0.1.0"
description = ""
authors = ["ryancartoon"]

[tool.poetry.dependencies]
python = "^3.8"
redis = "^4.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
